if((ENABLE_ASAN OR ENABLE_UBSAN OR ENABLE_COVERAGE) AND NOT FW_PLATFORM STREQUAL "host_posix")
    message(FATAL_ERROR "Sanitizers and coverage are host_posix validation features")
endif()

function(fw03_apply_runtime_checks target)
    if(MSVC)
        if(ENABLE_ASAN)
            target_compile_options(${target} PRIVATE /fsanitize=address)
            target_link_options(${target} PRIVATE /fsanitize=address)
        endif()
        if(ENABLE_UBSAN OR ENABLE_COVERAGE)
            message(FATAL_ERROR "UBSan and GCC coverage are not configured for MSVC")
        endif()
        return()
    endif()

    set(sanitizers "")
    if(ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()
    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_list)
        target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer_list}" -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE "-fsanitize=${sanitizer_list}" -fno-omit-frame-pointer)
    endif()

    if(ENABLE_COVERAGE)
        target_compile_options(${target} PRIVATE --coverage -O0 -g)
        target_link_options(${target} PRIVATE --coverage)
    endif()
endfunction()
